# Generated by Django 4.2.3 on 2023-07-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', null=True, upload_to=''),
        ),
    ]
